### ISSUE TITLE
Test with Emulsify Theme

### ISSUE THREAD

**Issue by backlineint** [backlineint/ui_patterns_pattern_lab#1]
Confirm that the module can recognize components from https://github.com/fourkitchens/emulsify Fix bugs as necessary, document any noteworthy findings.

**Comment by backlineint** [comment]
Just getting started here, but a few things I've run into thus far:

- UI Patterns requires that the ID contain only lowercase characters, numbers and underscores. So a pattern like 00-grid.yml won't validate.  Replacing - with _ in IDs seems like a reasonable way to work around this.  I've also considered adding a key that could be used to skip a pattern - could work as a last resort.
- As defined, a pattern like colors.twig that renders multiple items via a for loop isn't really something that the module can handle at the moment.
````
items:
  - name: $white
    value: white
  - name: $near-white
    value: '#f2f2f2'
  - name: $gray-lightest
    value: '#e5e5e5'
  - name: $gray-lighter
    value: '#ccc'
  - name: $gray-light
    value: '#999'
  - name: $gray
    value: '#666'
  - name: $gray-dark
    value: '#4c4c4c'
  - name: $gray-darker
    value: '#333'
  - name: $black
    value: black
````
```
<ul class="sg-colors">
  {% for item in items %}
    <li>
      <div class="sg-swatch" style="background: {{item.value}};"></div>
      <div class="sg-info">
        <span>{{item.value}}</span> <br/>
        <code>{{item.name}}</code>
      </div>
    </li>
  {% endfor %}
</ul>
{% if meta %}
  <p> <small>{{ meta.description }}</small> </p>
{% endif %}
```
I'll keep an eye on patterns like this - not sure if support needs to be added to the module, or this is more of a something that would be supported by nested sub-paterns on the drupal side.
